"""Add confirmed column to users table

Revision ID: 0757d8b61750
Revises: 1edff8c3bab4
Create Date: 2023-10-16 10:34:34.733694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0757d8b61750'
down_revision = '1edff8c3bab4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    # ### end Alembic commands ###
