"""add avatar_hash column to users

Revision ID: 51b4f4ab6a6d
Revises: c0452f3f0f38
Create Date: 2023-10-17 17:38:10.006023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51b4f4ab6a6d'
down_revision = 'c0452f3f0f38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    # ### end Alembic commands ###
